### PR TITLE
Release 0.9.41

### PR DESCRIPTION
**Pull request by chuckharmston**
Notable changes:

1. There was an option added to enable the experiment over the top of DNT or Tracking Protection.
1. Improved messaging when DNT, Tracking Protection, or private browsing mode are enabled.
1. Since the experiment is disabled by default when DNT or Tracking Protection is enabled and in private browsing mode, we now send the user token when the extension is enabled to get better related article recommendations.
1. Trending/popular articles are available when the "For You" section isn't able to be populated (e.g. at install time).

All of these changes are on master. @SoftVision-CosminMuntean, could you coordinate QA for this release? Thanks!

### CODE REVIEW

**Comment by SoftVision-PaulOiegas** [comment]
Hi @chuckharmston. For future requests please use the pi-request@mozilla.com alias or at least the experiments-qa@softvision.ro team alias. This helps us to better track all the requests and also avoid missing them. 
We would have missed this request if Cosmin would have been in PTO this week and not the next.

**Comment by SoftVision-CosminMuntean** [comment]
Hi guys,

We have finalized testing the latest Advance (0.9.45) version, here are the testing results:

### **Legend** ###
&#x26D4;  - blocker issue
&#x1F4D5; - major issue
&#x1F4D9; - normal issue
&#x1F4D2; - minor issue
&#x1F4D7; - enhancement

## New Issues ##
#87 - &#x26D4; The articles from "For You" section are duplicated in the "Read Next" section if an article is blocked when the "Read Next" section is not populated
- Also, it seems that the blocked article is still displayed in the "For You" section.

#84 - &#x1F4D5; Users may be mislead by the description from "Read Next" section if the "Override DoNotTrack" option is enabled
- It is not very clear whether the "Read Next" section should or should not be populated while the "Override DoNotTrack" option is enabled; 
In the current behavior, after you enable the "Override DoNotTrack" option, the "Read Next" section is only populated in the first session while you navigate through different websites. After the browser is restarted the section is no longer populated.

#86 - &#x1F4D9; Only the title of the "Read Next" section is displayed after the "Override DoNotTrack" option is enabled or the experiment it's installed
- The "Read Next" section is displayed entirely only after you navigate to a website or the Advance sidebar is closed and reopened.

#85 - &#x1F4D9; The previously custom options don't persist in a new Private Window after the "Override DoNotTrack" option is enabled

## Based on testing results we would suggest the next course of actions: ##
Considering the fact that all the mentioned issues are on the server side and we haven't found any issue related to the add-on, from the QA point of view we can release this version of it.

However, since the changes of the server were already deployed on production and there is nothing we can do now, we strongly recommend to fix the following issues as soon as possible: #87 (blocker), #84 (major), #86 (normal).

**Comment by chuckharmston** [comment]
@sg-laserlike we're ready to go here! Would you mind fixing the merge conflicts and pushing the big red button?

**Comment by sg-laserlike** [comment]
HI Chuck, it’s merged, but can’t find the big red button anywhere☹️

**Comment by chuckharmston** [comment]
I meant the big red button to merge :) It's being built now and should be live in production shortly.

**Comment by magebarf** [comment]
Is this supposed to have gone live by now? Firefox has not found any new updates for the addon since 8th of August, so just wonder if something has gone wrong or is just lagging a bit?

**Comment by chuckharmston** [comment]
@magebarf It is live. You can ask Firefox to look for updates in about:addons:

screen shot 2018-09-20 at 7 32 11 am

Of note, some antivirus software [has been known](https://bugzilla.mozilla.org/show_bug.cgi?id=1308251) to block add-on installs and updates.

**Comment by magebarf** [comment]
Yep, have done so daily since start of this week, still nothing listed...

image

Could it be a regional thing? Developer mode thing? I'm running "buck standard" end user Firefox, with a Swedish region account, but with a English Firefox locale.

**Comment by SoftVision-CosminMuntean** [comment]
@magebarf did you received any updates related to Advance experiment? Do you still have the 0.9.45237 version installed?
I'm trying to find if something is wrong with the add-on update.

**Comment by magebarf** [comment]
Firefox plugin not updated since august 8th.
image
Screenshot taken 5 seconds ago, still reporting same version number and date of update.

I've got to ask though; The version number in the addon title, is that the version of Laserlike, or of the addon itself? It seems to be in a quite different way of version numbering compared to the "9.41" being discussed here...  I guess it shouldn't matter, but I'm also unsure if Firefox does any type of version number validation/comparison to see if it considers something an update?

**Comment by SoftVision-CosminMuntean** [comment]
It's the version of the add-on. The latest version of the Advance add-on should be 0.9.4607.

@magebarf  Can you help me to investigate this and send me your Advance add-on version? In order to do this, navigate to "about:support" page and click the "Open Folder" button from the "Application Basics" section, row "Profile Folder". After the folder window is opened click the "extensions" folder and attach here the "support@laserlike.com.xpi" file.

**Comment by magebarf** [comment]
[support@laserlike.com.zip](https://github.com/LaserlikeInc/firefox-addon/files/2423539/support.laserlike.com.zip)
Sure, here it is. GitHub was not fond of the .xpi extension, so I changed it into .zip to be able to upload.

**Comment by SoftVision-CosminMuntean** [comment]
Thanks for providing this add-on! Indeed I have managed to reproduce the issue. The older version of the addon (0.9.45237) does not update to the latest version. 
I will let you know when we have more information and when this is fixed.

**Pull request merged**
